name: backup-actions
on: [push]
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: git-mirror-2
        uses: TheTipsyTurtle/mirror-action@master
        env:
          PUSH_ALL_REFS: "false"
        with:
          REMOTE: https://github.com/mahdiiix/CICD_test.git
          GIT_USERNAME: mahdiiix
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
